const CHANGE_SINGER_LIST = 'singer/CHANGE_SINGER_LIST';
const CHANGE_PAGE_COUNT = 'singer/CHANGE_PAGE_COUNT';
const CHANGE_ENTER_LOADING = 'singer/CHANGE_ENTER_LOADING';
const CHANGE_PULLUP_LOADING = 'singer/CHANGE_PULLUP_LOADING';
const CHANGE_PULLDOWN_LOADING = 'singer/CHANGE_PULLDOWN_LOADING';
const CHANGE_CATEGORY = 'singer/CHANGE_CATEGORY';
const CHANGE_ALPHA = 'singer/CHANGE_ALPHA';

export {
    CHANGE_SINGER_LIST,
    CHANGE_PAGE_COUNT,
    CHANGE_ENTER_LOADING,
    CHANGE_PULLUP_LOADING,
    CHANGE_PULLDOWN_LOADING,
    CHANGE_CATEGORY,
    CHANGE_ALPHA,
};